baseurl = "http://www.wtlinux.com/"
title = "wtlinux"
theme = "whiteplain"
languageCode = "en-us"
# Disqus shortname
disqusShortname = "wtlinux"
# google analytics tracking id
googleAnalytics = "UA-122643141-1"


pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2016 wtlinux"

[params]
  # Date format
  #dateFormat = "January 2, 2006"
  googleAnalytics = "UA-122643141-1"


# This is displayer in About page.
[params.author]
  name = "wang tian"
  # Gravatar or Abatar image
  #avatar = "/path/to/avatar"


  linkedin = "https://www.linkedin.com/in/%E7%94%B0-%E7%8E%8B-879609140/"
  github = "https://github.com/wtli"
  email = "976199267@qq.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  archive = "archives"

# Header Menu
[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 1

[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"


[permalinks]
	page = "/:title/"
	about = "/:filename/"